export const SET_CARTLIST = 'SET_CARTLIST'

export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST'

export const SET_CHECKED_LIST = 'SET_CHECKED_LIST'

export const SET_CHECKED_ADDRESS = 'SET_CHECKED_ADDRESS'
